# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.102
    - name: Restore dependencies
      run: dotnet restore ClassLibraryProjects/StringLibrary/StringLibrary.sln
    - name: Build 
      run: dotnet build ClassLibraryProjects/StringLibrary/StringLibrary.sln --no-restore
    - name: Test
      run: dotnet test ClassLibraryProjects/StringLibrary/StringLibrary.sln --no-build --verbosity normal
